---
title: "Student Notes"
format: html
---

## Week 4 Assessment: Quizzes, Labs, and Assignments

**Skill**:

- Each module has at least 1 lab and 1 assignment

**Knowledge**:

- Auto-graded MCQ Quiz on Tuesday (M1 & M2)
- Auto-graded MCQ Quiz on Thursday (M3 & M4 + few questions from M1 & M2)

**How do I get 100%?**:

Achievement of 100% requires understanding the material in the lab; which requires reading and review of the lab, as well as paying attention to the lecture that builds up to the lab. And then, doing the assignments. Review your work and check your understanding.

- **Bonus**: you are engaged with the material and the lecture.
- **Bonus**: you exhibit a high amount of effort in mastering the material. Example: doing the optional exercises like the ones in M1 Lab 3 (Tensors).

**How to mess things up?**:

- Cheat
- Sprinting through the lab without understanding the material
- Doing the lab at lecture time (you need to pay attention to the lecture to understand the material)

**Remember**: if you get stuck, ask the instructor for help. We are here to help you learn; not to judge you.
